# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6f63b7f58be7c3e2db1b627bbb513050b6ffd18759a9f0d21fca7c4d2e8b64265c56a9a3714df4ccf2dd23adc524901a739653d44eb10c7289c71791dc12919

test:
  secret_key_base: cfede983a552ade2bf5803cce1f841be4af4563a8a7ba8c8931542b47b9556648113ddda02c48d1eb6c5bea24e16ca0b4eb229ac5769006dc0b9e301de33cd63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
